# if this is a GNU GCC compiler, enable the C++xx features that the GCC version supports
if(CMAKE_COMPILER_IS_GNUCXX)
    # test for C++ > C++98
    include(CheckCXXCompilerFlag)
    check_cxx_compiler_flag("-std=c++11" COMPILER_SUPPORTS_CXX11)
    if(COMPILER_SUPPORTS_CXX11)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
        option(ENABLE_CXX11_ABI "Use the new C++-11 ABI, which is not backwards compatible." OFF)
        if(NOT ENABLE_CXX11_ABI)
            add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)
        endif()
    else()
        check_cxx_compiler_flag("-std=c++0x" COMPILER_SUPPORTS_CXX0X)
        if(COMPILER_SUPPORTS_CXX0X)
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
        endif()
    endif()
endif()
