set(CTEST_SOURCE_DIRECTORY .)
set(CTEST_BINARY_DIRECTORY .)
set(CTEST_COMMAND ctest)
execute_process(COMMAND ctest -D ExperimentalStart)
execute_process(COMMAND ctest -D ExperimentalUpdate)
execute_process(COMMAND cmake . -DENABLE_COVERAGE:BOOL=ON)
execute_process(COMMAND ctest -D ExperimentalBuild -C Debug)
execute_process(COMMAND ctest -D ExperimentalTest -C Debug)
execute_process(COMMAND ctest -D ExperimentalMemCheck)
execute_process(COMMAND ctest -D ExperimentalCoverage)
execute_process(COMMAND ctest -D ExperimentalSubmit)
