#######################################################################################################
#  macro to detect osg version and setup variables accordingly
#######################################################################################################
#MACRO(DETECT_OSG_VERSION)

OPTION(APPEND_OPENSCENEGRAPH_VERSION "Append the OSG version number to the osgPlugins directory" ON)

# detect if osgversion can be found
FIND_PROGRAM(OSG_VERSION_EXE NAMES osgversion HINTS ${OSG_DIR}/bin)
IF(OSG_VERSION_EXE AND ((NOT OPENSCENEGRPAH_MAJOR_VERSION) OR (NOT OPENSCENEGRAPH_MINOR_VERSION) OR (NOT OPENSCENEGRAPH_PATCH_VERSION)))
    # MESSAGE("OSGVERSION IS AT ${OSG_VERSION_EXE}")
    # get parameters out of the osgversion; note need on UNIX to set LD_LIBRARY_PATH
    IF(UNIX AND IS_DIRECTORY "${OSG_DIR}/lib64")
        SET(OLD_LD_LIBRARY_PATH $ENV{LD_LIBRARY_PATH})
        SET(ENV{LD_LIBRARY_PATH} "${OLD_LD_LIBRARY_PATH}:${OSG_DIR}/lib64")
    ENDIF()
    EXECUTE_PROCESS(COMMAND ${OSG_VERSION_EXE} --major-number OUTPUT_VARIABLE OPENSCENEGRAPH_MAJOR_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE)
    EXECUTE_PROCESS(COMMAND ${OSG_VERSION_EXE} --minor-number OUTPUT_VARIABLE OPENSCENEGRAPH_MINOR_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE)
    EXECUTE_PROCESS(COMMAND ${OSG_VERSION_EXE} --patch-number OUTPUT_VARIABLE OPENSCENEGRAPH_PATCH_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE)
    EXECUTE_PROCESS(COMMAND ${OSG_VERSION_EXE} --so-number OUTPUT_VARIABLE OPENSCENEGRAPH_SOVERSION OUTPUT_STRIP_TRAILING_WHITESPACE)
    EXECUTE_PROCESS(COMMAND ${OSG_VERSION_EXE} --openthreads-soversion-number OUTPUT_VARIABLE OPENSCENEGRAPH_OT_SOVERSION OUTPUT_STRIP_TRAILING_WHITESPACE)
    #EXECUTE_PROCESS(COMMAND ${OSG_VERSION_EXE} Matrix::value_type OUTPUT_VARIABLE OSG_USE_FLOAT_MATRIX OUTPUT_STRIP_TRAILING_WHITESPACE)
    #EXECUTE_PROCESS(COMMAND ${OSG_VERSION_EXE} Plane::value_type OUTPUT_VARIABLE OSG_USE_FLOAT_PLANE OUTPUT_STRIP_TRAILING_WHITESPACE)
    #EXECUTE_PROCESS(COMMAND ${OSG_VERSION_EXE} BoundingSphere::value_type OUTPUT_VARIABLE OSG_USE_FLOAT_BOUNDINGSPHERE OUTPUT_STRIP_TRAILING_WHITESPACE)
    #EXECUTE_PROCESS(COMMAND ${OSG_VERSION_EXE} BoundingBox::value_type OUTPUT_VARIABLE OSG_USE_FLOAT_BOUNDINGBOX OUTPUT_STRIP_TRAILING_WHITESPACE)
    IF(UNIX AND IS_DIRECTORY "${OSG_DIR}/lib")
        SET(ENV{LD_LIBRARY_PATH} ${OLD_LD_LIBRARY_PATH})
    ENDIF(UNIX AND IS_DIRECTORY "${OSG_DIR}/lib")

    # setup version numbers if we have osgversion
    SET(OPENSCENEGRAPH_MAJOR_VERSION "${OPENSCENEGRAPH_MAJOR_VERSION}" CACHE STRING "OpenSceneGraph major version number" FORCE)
    SET(OPENSCENEGRAPH_MINOR_VERSION "${OPENSCENEGRAPH_MINOR_VERSION}" CACHE STRING "OpenSceneGraph minor version number" FORCE)
    SET(OPENSCENEGRAPH_PATCH_VERSION "${OPENSCENEGRAPH_PATCH_VERSION}" CACHE STRING "OpenSceneGraph patch version number" FORCE)
    SET(OPENSCENEGRAPH_SOVERSION "${OPENSCENEGRAPH_SOVERSION}" CACHE STRING "OpenSceneGraph so version number" FORCE)
    SET(OPENSCENEGRAPH_OT_SOVERSION "${OPENSCENEGRAPH_OT_SOVERSION}" CACHE STRING "OpenThreads so version number" FORCE)

ENDIF(OSG_VERSION_EXE AND ((NOT OPENSCENEGRPAH_MAJOR_VERSION) OR (NOT OPENSCENEGRAPH_MINOR_VERSION) OR (NOT OPENSCENEGRAPH_PATCH_VERSION)))

# Initialize the version numbers to being empty.  If they were set by osgversion, they will be left alone
SET(OPENSCENEGRAPH_MAJOR_VERSION "" CACHE STRING "OpenSceneGraph major version number")
SET(OPENSCENEGRAPH_MINOR_VERSION "" CACHE STRING "OpenSceneGraph minor version number")
SET(OPENSCENEGRAPH_PATCH_VERSION "" CACHE STRING "OpenSceneGraph patch version number")
SET(OPENSCENEGRAPH_SOVERSION "" CACHE STRING "OpenSceneGraph so version number")
SET(OPENSCENEGRAPH_OT_SOVERSION "" CACHE STRING "OpenThreads so version number")

IF(NOT OPENSCENEGRAPH_MAJOR_VERSION STREQUAL "" AND NOT OPENSCENEGRAPH_MINOR_VERSION STREQUAL "" AND NOT OPENSCENEGRAPH_PATCH_VERSION STREQUAL "")
    SET(OPENSCENEGRAPH_VERSION ${OPENSCENEGRAPH_MAJOR_VERSION}.${OPENSCENEGRAPH_MINOR_VERSION}.${OPENSCENEGRAPH_PATCH_VERSION})
ELSE(NOT OPENSCENEGRAPH_MAJOR_VERSION STREQUAL "" AND NOT OPENSCENEGRAPH_MINOR_VERSION STREQUAL "" AND NOT OPENSCENEGRAPH_PATCH_VERSION STREQUAL "")
    SET(OPENSCENEGRAPH_VERSION)
ENDIF(NOT OPENSCENEGRAPH_MAJOR_VERSION STREQUAL "" AND NOT OPENSCENEGRAPH_MINOR_VERSION STREQUAL "" AND NOT OPENSCENEGRAPH_PATCH_VERSION STREQUAL "")

MARK_AS_ADVANCED(OPENSCENEGRAPH_VERSION)


IF(APPEND_OPENSCENEGRAPH_VERSION AND OPENSCENEGRAPH_VERSION)
    SET(OSG_PLUGINS "osgPlugins-${OPENSCENEGRAPH_VERSION}"  CACHE STRING "" FORCE)
    IF(VERBOSE)
        MESSAGE(STATUS "Plugins will be installed under osgPlugins-${OPENSCENEGRAPH_VERSION} directory.")
    ENDIF(VERBOSE)
ELSE(APPEND_OPENSCENEGRAPH_VERSION AND OPENSCENEGRAPH_VERSION)
    SET(OSG_PLUGINS  CACHE STRING "" FORCE)
ENDIF(APPEND_OPENSCENEGRAPH_VERSION AND OPENSCENEGRAPH_VERSION)

MARK_AS_ADVANCED(OSG_PLUGINS)
