if(TARGET GEOS::geos AND TARGET GEOS::geos_c)
    if(WIN32)
        vsi_install_target(GEOS::geos ThirdPartyLibs)
        vsi_install_target(GEOS::geos_c ThirdPartyLibs)
    else()
        get_target_property(_GEOS_SO GEOS::geos IMPORTED_LOCATION_RELEASE)
        get_filename_component(_GEOS_LIB_DIR "${_GEOS_SO}" DIRECTORY)
        get_symlinks("${_GEOS_LIB_DIR}/libgeos.so" _GEOS_LIBS)
        install(PROGRAMS ${_GEOS_LIBS} DESTINATION "${INSTALLSETTINGS_SHARED_LIBRARY_DIR}" COMPONENT ThirdPartyLibs)
        get_symlinks("${_GEOS_LIB_DIR}/libgeos_c.so" _GEOS_LIBS)
        install(PROGRAMS ${_GEOS_LIBS} DESTINATION "${INSTALLSETTINGS_SHARED_LIBRARY_DIR}" COMPONENT ThirdPartyLibs)
    endif()
endif()
